### ISSUE TITLE
Feature Request: Grammar Sampling in TGI

### ISSUE THREAD

**Issue by axenov** [MeetKai/functionary#217]
## Description
I would like to know if there are plans to support grammar sampling in TGI. 

## Background

TGI has integrated `outlines` to apply JSON and regex grammar to the output. Moreover, recently they integrated the function calling into their OpenAI-compatible message API. It also uses grammar but it seems that it has a fixed prompt template for functions.

## Request

Are there any plans to expand the support for grammar sampling in TGI. How will the accuracy of the functionary models degrade if I directly use TGI message API?

**Comment by jeffreymeetkai** [comment]
Hi, there is no plan currently to support grammar sampling in TGI due to limited bandwidth.

**Challenges to support grammar sampling**
To support grammar sampling, we will need to implement the backbone finite-state machines that switches between function name generation, parameter generation stages etc. within TGI's codebase for every prompt template which is a significant work.

**How to use TGI message API with Functionary**
Thank you for pointing out the recent function calling integration into TGI. After a brief read of the [code](https://github.com/huggingface/text-generation-inference/blob/main/router/src/server.rs#L1053-L1079), it seems that the tools definition is generated as JSON schema (Do let me know if I'm wrong). This may be problematic as the tools definition in Functionary is generated as Typescript schema. In addition, it is also unclear yet how the raw response is parsed into the ChatCompletion object without writing a wrapper for it. More investigation is needed to find this out.

A current workaround will be to generate the functions schema as a system message and prepend all the system messages before your messages in the client side before sending the final messages to the TGI endpoint. A similar pipeline is done in `server_tgi.py` [here](https://github.com/MeetKai/functionary/blob/c8484eb2d23afe873892757641cc52a4175a7f45/server_tgi.py#L129-L131). Note that it forms the prompt string directly because we did not use messages API. You will need to convert the prompt back to list of messages to use messages API.
