### ISSUE TITLE
(Multi)-LoRAs on top of functionary AWQ with vLLM

### ISSUE THREAD

**Issue by l4b4r4b4b4** [MeetKai/functionary#241]
If I load a lora adapter of let's I.e. continued pre-training run on top of an awq quant of functionary 3.2 loaded with vllm 0.5.6 would it

1. Technically load the model
2. Preserve the function calling capability?

Should I rather fine-tune and realign with functionary dataset, which I assum we is open source?

**Comment by jeffrey-fong** [comment]
1. If you are asking about during training, the model weights will still need to be loaded for LoRA training but only the LoRA adapter weights will have the activation and optimizer states. If you are asking about during inference, the model weights will still need to be loaded too because they are needed for the LoRA weights to be added to it.

2. We are not sure how much of the function-calling capability will be preserved if you perform either continued pretraining or continued fine-tuning on top of Functionary as we have not tried this yet. I think you can potentially try continued fine-tuning on Functionary with a smaller dataset specific to your use case. However, I'm not so optimistic about continued pretraining as you are essentially reverting the model back to a base model.

`Should I rather fine-tune and realign with functionary dataset, which I assum we is open source?`
We do not plan to release our dataset. Thank you.
