### ISSUE TITLE
`generateMessage` does not parse the function call correctly within messages

### ISSUE THREAD

**Issue by anthonysanchezmk** [MeetKai/functionary#28]
https://github.com/MeetKai/functionary/blob/main/functionary/inference.py#L89-L100

The function call will not be correctly parsed if its used in the middle of the text.

**Comment by unaidedelf8777** [comment]
unfortunately, unlike the ChatGPT Code Interpreter or similar products, this model isn't designed to execute functions within a standard text response. Creating a dataset to enable such functionality is a complex task, especially since it would need to be synthetic. Additionally, the scraping access that was available through ShareGPT was discontinued before the Code Interpreter feature was introduced, meaning that any data would need to be generated through models like llama2, and then heavily filtered to actually get high quality data. 

I am actively working on the dataset for this, but it's a challenging process. If you've managed to get the model to make function calls within text responses, I'd be very interested in seeing the prompt or conversation that led to this behavior.

As for parsing errors, achieving the level of parsing you're referring to would require the introduction of special tokens. This is a non-trivial task that would necessitate large amounts of data and additional pre-training. Therefore, it's currently not feasible to implement such parsing capabilities.
