### ISSUE TITLE
Missing "config.json" for Huggingface hosted model at /meetkai/functionary-7b-v2-GGUF

### ISSUE THREAD

**Issue by vand-io** [MeetKai/functionary#75]
I'm trying to use functionary's server.py with the --model /meetkai/functionary-7b-v2-GGUF which throws an error. (Can't use vLLM due to limited GPU memory).

`python3 server.py --model /meetkai/functionary-7b-v2-GGUF`

throws:

`OSError: meetkai/functionary-7b-v2-GGUF does not appear to have a file named config.json. Checkout 'https://huggingface.co/meetkai/functionary-7b-v2-GGUF/main' for available files.`

It looks like the config.json needs to be included at HuggingFace for this to work.

**Comment by jeffreymeetkai** [comment]
Hi,

Unfortunately, both our server scripts do not support loading GGUF models (I think GGUF is exclusively for llama.cpp) and we also do not have any plans currently to implement a llama.cpp server due to the difficulty of maintaining 3 servers. However, we have provided an example to use llama.cpp for inference [here](https://github.com/MeetKai/functionary?tab=readme-ov-file#llama_cpp-inference).

Hope it helps!

**Comment by vand-io** [comment]
Makes sense.  Now I see the model at [meetkai/functionary-7b-v2 ](https://huggingface.co/meetkai/functionary-7b-v2/tree/main) which I'll try with your own server.

I've tried using functionary with llama.cpp (and llama-cpp-python) but with poor results but that's another issue...

**Comment by jeffreymeetkai** [comment]
@vand-io Did you use the GGUF model with llama.cpp that resulted in poor results? Feel free to let us know what are some of the poor results so our team can look into it too. Thanks!

**Comment by vand-io** [comment]
Thanks @jeffreymeetkai. I opened a new issue #77 to detail the challenges using the GGUF model with llama.cpp and llama-cpp-python.
